name: Secure CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
       
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Check suspicious commands in repo
        run: |
         echo "Checking for suspicious CI/CD commands and ports..."
         if grep -RInE "(curl .*http|wget .*http|nc |netcat|bash .*http|sh .*http|:4444|:1337|:9001|:8081)" . \
         --exclude-dir=.git \
         --exclude=.github/workflows/security-pipeline.yml; then
         echo "Suspicious command or port found. Failing pipeline."
         exit 1
         else
         echo "No suspicious commands or ports found."
         fi

      - name: Verify pipeline works
        run: echo "Secure CI/CD pipeline started successfully"

      - name: Run Semgrep SAST
        uses: returntocorp/semgrep-action@v1

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pip-audit

      - name: Run pip-audit (SCA)
        run: pip-audit || true

      - name: Run Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/secure-cicd-lab:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/secure-cicd-lab:latest
      
      - name: Scan Docker image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/secure-cicd-lab:latest
          format: table
          output: trivy-report.txt
        continue-on-error: true
      

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Sign Docker image with Cosign
        run: cosign sign --yes ghcr.io/${{ github.repository_owner }}/secure-cicd-lab:latest
      
      - name: Verify Docker image signature
        run: |
         cosign verify ghcr.io/${{ github.repository_owner }}/secure-cicd-lab:latest \
         --certificate-identity-regexp ".*" \
         --certificate-oidc-issuer https://token.actions.githubusercontent.com

      - name: Run OWASP ZAP (DAST)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://example.com"
        continue-on-error: true